Repository codurance/site, pull requests merged in 2019-06, with the labels that each got.

#1332 Podcast 14 mentorship
  src/_podcasts/2019-06-11-mentorship.md
Labels: do-not-merge-yet

#1342 Added case study for Asos
  src/_i18n/en.yml
  src/assets/custom/img/case-study/ASOS.png
  src/assets/custom/img/case-study/asos.png
Labels: do-not-merge-yet

#1343 Multiple case studies
  src/_data/clients.yml
  src/_i18n/en.yml
  src/_layouts/case_study.html
  src/clients/index.html
  src/clients/projects/software-craftsmanship-at-asos.html
  src/clients/projects/software-craftsmanship-at-coniq.html
Labels: do-not-merge-yet

#1330 remove the obsolete rake tasks
  Dockerfile
  README.md
  Rakefile
  docker-compose.override.yml
Labels: do-not-merge-yet, help wanted

#1345 Tesco case studies
  src/_data/clients.yml
  src/_i18n/en.yml
  src/_layouts/case_study.html
  src/clients/index.html
  src/clients/projects/software-craftsmanship-at-tesco-forecasting.html
  src/clients/projects/software-craftsmanship-at-tesco-scheduling.html
Labels: do-not-merge-yet

#1337 Added new address (to be merged on Monday 24th)
  src/_includes/footer.html
  src/company/index.html
  src/policies/privacy.html
Labels: do-not-merge-yet

#1360 Add Instagram icon and link to footer
  src/_includes/footer.html
Labels: quick-win
